### ISSUE TITLE
No line space between paragraphs…

### ISSUE THREAD

**Issue by PerspexSphinx** [alb42/Legadon#1]
**Thanks**, for this really useful program. 

Just noticed a few quirks…  
There's no line space displayed between paragraphs (\<p>  \</p>)?   
 and the space between paragraphs really helps in readability.

For me I find the page turning gadgets are a little too small, at least on my OS 3.2 rtg desktop.
Also it would be nice to be able to use the cursor keys to turn the pages and to scroll the pages up and down.

Oh, does the name "Legadon" mean anything? 

**Thanks**, once again, it's **Wonderful** to be able to read ePubs on my favorite OS.

**Comment by alb42** [comment]
the commit 7eb6d88b2024c518de21821e06b6759120561fa8 fixed that
